# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이승민
title: 5년차 자바, 스프링 백엔드 엔지니어
email: sml7179@naver.com
# website: https://roomconerdeveloper.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lsm7179
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://roomconerdeveloper.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# <mark>AWS</mark> and <mark>Eating Pizza</mark>
about_profile_image: images/lsm.jpg
about_content: | # this will include new lines to allow paragraphs
  더 좋은 코드를 위해 고민하는 Java & Spring 기반의 소프트엔지니어 이승민입니다.
  솔루션 SI/SM을 업무했으며 주로 비즈니스 기능을 개선, 개발하고 배포하는 업무를 했습니다.

  저는 끊임없는 배움과 코드품질을 높이는것을 중요하게 생각합니다.
  개발경험을 위해 <mark>Node와 React-Native로 사이드 프로젝트</mark>를 만들었습니다.
  <mark>코드 리뷰</mark>와 <mark>테스트 코드</mark>에 관심을 가져 프로젝트에 적용했습니다.

  배움을 위해서 우아한테크캠프Pro3기 과정을 이수 하였고 열심히 한 결과 <mark>우수수료생</mark>으로 선발 되었습니다.

  감사합니다.

content:
#  - title: 경력사항 # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: 신한항업
#        # link: github.com/sproogen
#        # link_text: Project Website
#        # additional_links:
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: 경력사항 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 신한항업
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 공공사업부 / 주임
         <br/> 웹 개발 업무
        caption: 2020.05 - 2021.11
        quote: >
          측량업관리시스템, 측량업종합관리시스템, 도시계획시스템 개발 및 유지보수
        description: |
          - [테스트 코드](https://roomconerdeveloper.tistory.com/124?category=846816),
            [코드 리뷰](https://roomconerdeveloper.tistory.com/123?category=840724) 도입하여 개발 환경 개선
          - 측량업 시스템 개발, 프로젝트 일정 관리, 배치 서비스 유지보수
      - job_title: 배치 스케줄 강제종료 기능 개발

        dates:
        quote: >
          자바 스케줄러 구현 및 강제종료 구현
        description: |
          - ThreadPoolTaskScheduler를 이용하여 자바 스케줄러 구현 및 강제종료 구현
          - interrupt Exception을 사용하여 강제 종료
          - [자바 스케줄러 구현 및 강제종료 구현](https://roomconerdeveloper.tistory.com/116)
      - sub_title: k-Geo플랫폼 측량업 관리 시스템
        caption: 2021.05 - 2021.11
        quote: >
          측량업, 측량업체 등록 관리 시스템
        description: |
          - 테스트코드, 코드 리뷰 도입
          - Rest API 개발
          - 레포팅툴 api 연동
          - 요구사항 분석 및 설계
      - sub_title: KILP 시스템 개발
        caption: 2021.01 - 2021.04
        quote: >
          도시 계획 관리 시스템
        description: |
          - 용역성과 CRUD 메뉴 개발
          - 엑셀 일괄 업로드 개발
          - 통계 조회, 엑셀 다운로드 개발
          - 오픈레이어스 맵 스크립트 api 연동
      - sub_title: 측량업정보 종합관리체계 시스템 구축 4차 및 유지관리
        caption: 2020.05 - 2020.12
        quote: >
          공간정보기술자가 경력신고, 증명서 발급, 우편물 확인 하는 시스템으로
          공간기술자 등급및 분야를 법령에 맞게 산정 하여 관리 할 수 있습니다.
        description: |
          - 공간정보기술자 관리 설계, 개발
          - 신규 기능 추가, 기존 기능 버그 수정
            - 경력 신고 관리
            - 등급 산정 기능 개발
            - 측량업기능사 등급 산정 기능 개선(한달에 1건 오류 -> 0건으로 개선)
            - 기능별 중복 코드 리팩터링을 통해 구조 개선 및 쿼리 튜닝
          - 배치서비스 유지보수
      - layout: left
        title: 한국문헌정보기술
        sub_title: 개발팀 / 주임
          <br/> 웹 개발 업무
        caption: 2017.03 - 2019.11
        quote: >
          감어인 솔루션 개발, 유지보수 및 운영 관리
        description: |
          - 감어인M 솔루션 서비스페이지 기능 개발
          - 레거시 시스템에서 감어인M 시스템으로 고도화 개발
          - 오라클DB에서 큐브리드DB로 데이터 마이그레이션
          - 바코드 프린터 api 연동
          - 엑셀 다운로드 개발
          - 검색엔진 api 연동 및 개발
          - 슬로우 쿼리를 찾아 인덱스 생성, 조인관계 개선 5초 -> 0.2초로 단축
          - 솔루션 유지보수

  - title: 학력 및 교육 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 우아한테크캠프Pro3기
        # sub_title:
        caption: 2021.11 - 2021.12
        quote: >
          우수수료생으로 수료.
        description: |
          [교육후기](https://roomconerdeveloper.tistory.com/128)

          우아한테크캠프 Pro 과정은 아래 경험을 얻었습니다.

          클린코드 개발, JPA 기반 웹 개발, 단위 인수 테스트를 이용한 TDD ATDD 경험,

          레거시 코드를 안정적으로 리팩터링, 시스템 아키텍처를 설계 및 운영,

          웹 전반에 대해 최적화할 대상을 살펴보고 서버를 튜닝하는 경험

      - layout: left
        title: KG아이티
        sub_title: 교육이수내역
        caption: 2016.10 - 2017.02
        quote: >
          웹 프로그래머 개발과정 수료
        description: |
          Java, Javascript, Spring, Mybatics, Oracle 등등을 사용하여 웹프로그래머 개발 과정을 이수하였습니다.

      - layout: left
        title: 동양미래대학
        caption: 2011.03 - 2014.02
        # sub_title: 반도체전자과
        quote: >
          반도체전자과 전문학사 졸업
        # description: | # this will include new lines to allow paragraphs
  - title: 사이드 프로젝트
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 샤워 필터 모니터링
        caption: 2020.07 - 2020.12
        quote: >
          사용 기술 : Node, React-Native, MongoDB, Docker
        description: |
          샤워필터를 사용시간에 따라 얼마나 남았는지 표현해주는 웹앱

          DB설계, 개발, 서버 설치를 맡아서 진행하였습니다.

          [샤워 필터 모니터링](https://roomconerdeveloper.tistory.com/47?category=862240)
  - title: 기타 활동
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 자동 배포 구축
        quote: >
          AWS EC2 + Jenkins + Git hook을 이용한 자동 배포 구축 해보았습니다.
        description: |
          [자동배포후기](https://roomconerdeveloper.tistory.com/26)
      - layout: left
        title: 개인 블로그
        quote: >
          공부했던것, 업무중에 정리한 내용을 기록한 블로그 입니다.
        description: |
          [방구석개발자 블로그](https://roomconerdeveloper.tistory.com/)

#  - title: 그 외 활동
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title:
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
